#pragma once

#include <functional>
#include <qdatetime.h>
#include <qfilesystemwatcher.h>
#include <qnetworkaccessmanager.h>
#include <qobject.h>
#include <qqmlintegration.h>
#include <qstring.h>
#include <qtimer.h>
#include <qvariant.h>

namespace burl {

// Pulls playlists + recently-played from the Spotify Web API.
// Credentials (client_id, client_secret, refresh_token) come from
// ~/.config/burl/spotify-token.json — generated by the
// burl-spotify-auth helper. If the file is missing we just stay
// empty; nothing fatal.
class SpotifySources : public QObject {
    Q_OBJECT
    QML_ELEMENT
    QML_SINGLETON

    Q_PROPERTY(QVariantList playlists READ playlists NOTIFY playlistsChanged)
    Q_PROPERTY(QVariantList recents READ recents NOTIFY recentsChanged)
    Q_PROPERTY(bool authed READ authed NOTIFY authedChanged)

public:
    explicit SpotifySources(QObject* parent = nullptr);

    [[nodiscard]] QVariantList playlists() const { return m_playlists; }
    [[nodiscard]] QVariantList recents() const { return m_recents; }
    [[nodiscard]] bool authed() const { return !m_refreshToken.isEmpty(); }

    Q_INVOKABLE void reload();
    // Begins playback of a Spotify URI on the active device. URIs
    // look like "spotify:track:...", "spotify:playlist:...", etc.
    Q_INVOKABLE void play(const QString& uri);

signals:
    void playlistsChanged();
    void recentsChanged();
    void authedChanged();

private:
    void loadCreds(std::function<void(bool)> done = {});
    void refreshAccessToken(std::function<void(bool)> done);
    void fetchPlaylists();
    void fetchRecents();
    QNetworkRequest authed(const QString& url) const;

    QString m_passStorePath;     // ~/.password-store/burl/spotify.gpg
    QString m_clientId;
    QString m_clientSecret;
    QString m_refreshToken;
    QString m_accessToken;
    QDateTime m_accessExpiry;

    QVariantList m_playlists;
    QVariantList m_recents;

    QNetworkAccessManager m_nam;
    QFileSystemWatcher m_watcher;
    QTimer m_refreshTimer;
    // Startup-race backoff: on system boot quickshell sometimes wins the
    // race against pam-gnupg's gpg-agent socket, so the ctor's first
    // `pass show` fails with "No such file or directory". Retry a handful
    // of times before giving up — the QML launcher-open retry then covers
    // the rare remaining case.
    QTimer m_bootRetryTimer;
    int m_bootRetriesLeft = 0;
};

} // namespace burl
